# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/embulk-parser-avro

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew test

      - store_test_results:
          path: ~/embulk-parser-avro/embulk-parser-avro/build/test-results
      - store_test_results:
          path: ~/embulk-parser-avro/embulk-guess-avro/build/test-results

  embulk-09:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/embulk-parser-avro
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      EMBULK_VERSION: 0.9.23

    steps:
      - checkout

      - restore_cache:
          keys:
            - embulk-v1-0.9.23

      - run: |
          if [ -f ~/embulk ]; then
            echo "~/embulk exists"
          else
            curl -o ~/embulk -L https://dl.embulk.org/embulk-${EMBULK_VERSION}.jar
          fi

      - save_cache:
          paths:
            - ~/embulk
          key: embulk-v1-0.9.23

      - run: chmod +x ~/embulk

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew gem

      - run:
          name: run-embulk-parser
          command: ~/embulk run -I ~/embulk-parser-avro/embulk-parser-avro/build/gemContents/lib config_acceptance.yml
          working_directory: ~/embulk-parser-avro/resources
      - run:
          name: run-embulk-guess
          command: ~/embulk guess -I ~/embulk-parser-avro/embulk-guess-avro/build/gemContents/lib -I ~/embulk-parser-avro/embulk-parser-avro/build/gemContents/lib config_guess_acceptance.yml
          working_directory: ~/embulk-parser-avro/resources

  embulk-011:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/embulk-parser-avro
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SKIP_SIGNING: true
      EMBULK_VERSION: 0.11.0
      JRUBY_VERSION: "9.3.10.0"
      JRUBY_PATH: ~/jruby.jar

    steps:
      - checkout

      - restore_cache:
          keys:
            - embulk-v1-0.11.0

      - run: |
          if [ -f ~/embulk.jar ]; then
            echo "~/embulk.jar exists"
          else
            curl -o ~/embulk.jar -L https://dl.embulk.org/embulk-${EMBULK_VERSION}.jar
          fi

      - save_cache:
          paths:
            - ~/embulk.jar
          key: embulk-v1-0.11.0

      - restore_cache:
          keys:
            - jruby-v1-9.3.10.0

      - run: |
          if [ -f ~/jruby.jar ]; then
            echo "~/jruby.jar exists"
          else
            curl -o ~/jruby.jar -L https://repo1.maven.org/maven2/org/jruby/jruby-complete/${JRUBY_VERSION}/jruby-complete-${JRUBY_VERSION}.jar
          fi

      - save_cache:
          paths:
            - ~/jruby.jar
          key: jruby-v1-9.3.10.0

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew publishEmbulkPluginMavenPublicationToMavenLocal

      - run: cp embulk-parser-avro/build/publications/embulkPluginMaven/pom-default.xml pom.xml

      - restore_cache:
          keys:
            - m2-v2-{{ checksum "pom.xml" }}

      - run: mvn dependency:resolve

      - save_cache:
          paths:
            - ~/.m2
          key: m2-v2-{{ checksum "pom.xml" }}

      - run: ./gradlew generateEmbulkProperties
      - run: cat .embulk/embulk.properties

      - run:
          name: run-embulk-parser
          command: java -jar ~/embulk.jar run config_acceptance.yml
          working_directory: ~/embulk-parser-avro/resources
      - run:
          name: run-embulk-guess
          command: java -jar ~/embulk.jar guess config_guess_acceptance.yml
          working_directory: ~/embulk-parser-avro/resources

workflows:
  version: 2.1
  test:
    jobs:
      - build
      - embulk-09
      - embulk-011
